//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dz_Library2_multi_table__DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Author_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Publishing_Id { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Publishings Publishings { get; set; }

        // переопределяем метод ToString()
        public override string ToString()
        {
            return $"(Id) {Id} Книга {Name} Автор {Authors.FirstName} {Authors.LastName} Категория {Categories.Name} Издательство {Publishings.Name}";
        }
    }
}
